### ISSUE TITLE
Week 3 project advances

### ISSUE THREAD

**Issue by DavidCalles** [DavidCalles/Wi-Fi-Analizer-Robot#1]
In the third week the following tasks will be accomplished:

- Basic ultrasonic sensor interfacing (retrieving data in python or C).
- Basic video feed acquisition (python with OpenCV).
- Basic WIFI signal data (maybe python or bash).
- Basic motor control code in C.
- Update the README file with a brief description.
- Basic Website (or research on it)

**Comment by DavidCalles** [comment]
On my end, I uploaded a basic working code for the ultrasonic sensor, and got the raspberry correctly set up. 
Also, as a team effort we retrieved video frames from a web camera using opencv.

**Comment by kjaskaran** [comment]
I updated the README file with a description of project design and team details. Also created a new branch (WebInterface) with a web-app folder, which is a basic design template for the web-app of this project.

**Comment by peakymonk** [comment]
I have written the C code for DC/TT motor functions and pushed into the github.

**Comment by MReyes-1** [comment]
Created a bash code to get and extract wi-fi information and generate a .json containing the information.

First challenge finding a way to get the wifi information.
https://www.cyberciti.biz/tips/linux-find-out-wireless-network-speed-signal-strength.html
used the iwconfig command and a grep to get the decired files

Second challenge was to format (trim, remove characters, undesired spaces, etc) from the information retrieved and saved.
find and replace
https://www.cyberciti.biz/faq/how-to-use-sed-to-find-and-replace-text-in-files-in-linux-unix-shell/
delete leading spaces
https://www.cyberciti.biz/tips/delete-leading-spaces-from-front-of-each-word.html
delete training spaces
https://stackoverflow.com/questions/4438306/how-to-remove-trailing-whitespaces-with-sed
add charters to the end of all lines
https://unix.stackexchange.com/questions/527241/add-at-the-end-of-each-line
generate a json from a csv
https://stackoverflow.com/questions/44780761/converting-csv-to-json-in-bash

revised the parts list to include a stereoscopic camera and fin another chassis as the original one is not available for shipping
