### ISSUE TITLE
Troubleshooting camera access from the Raspberry Pi's MIPI Port

### ISSUE THREAD

**Issue by kjaskaran** [DavidCalles/Wi-Fi-Analizer-Robot#19]
Neither of the cameras are working properly. Working to fix it...

**Comment by DavidCalles** [comment]
Camera port worked fine since the single camera worked.
The I2C port worked fine since I tested it with an accelerometer I2C sensor.
Conclusion: The stereo camera was discarded, and a Lidar sensor will be used.
