### ISSUE TITLE
Testing and Researching Basic SLAM code

### ISSUE THREAD

**Issue by DavidCalles** [DavidCalles/Wi-Fi-Analizer-Robot#25]
We want to be able to do some basic Mapping on the lidar images we receive

**Comment by DavidCalles** [comment]
https://github.com/AdroitAnandAI/SLAM-on-Raspberry-Pi

**Comment by DavidCalles** [comment]
Part of the time spent here was mainly in making the LIDAR work on our linux interface. It didnt worked properly on Native Ubuntu, it did work in WSL, and it is now working on the raspberry pi

**Comment by MReyes-1** [comment]
Test the LIDAR Natively in Ubuntu without success
Tested the LIDAR in WSL successfully

**Comment by DavidCalles** [comment]
The SLAM code works without any problem in the Raspberry Pi
