### ISSUE TITLE
Write and test a Calibration Algorithm for the camera

### ISSUE THREAD

**Issue by DavidCalles** [DavidCalles/Wi-Fi-Analizer-Robot#3]

**Comment by DavidCalles** [comment]
I used some code I previously wrote in:
**https://github.com/DavidCalles/Laser-line-3D-Scanner**
And modified it to calibrate a camera based on a set of images. 
This particular calibration is for compensating a lenses particular radial distortion. Which will be necessary when turning the stereo vision into a depth map.

**Comment by kjaskaran** [comment]
This works properly in a PC environment, creating follow case to test it out in the raspberry
