### ISSUE TITLE
Write and test DC/TT motor drivers code

### ISSUE THREAD

**Issue by DavidCalles** [DavidCalles/Wi-Fi-Analizer-Robot#5]

**Comment by peakymonk** [comment]
The C code for DC/TT motor driver is written and pushed into the github. The code is not tested.

**Comment by DavidCalles** [comment]
Hey Govinda, since the robot just arrived, we can probably test the code with one of the motors. Maybe our next step here would be for you to connect remotely to the raspberry pi through VNC

**Comment by peakymonk** [comment]
While working with the robot we purchased, I found out that the pins assigned for motor function is limited, and it works with PWM. 
So this week I am going to work on the motor function with the possible coding with the hat code.
