### ISSUE TITLE
Assemble robot vehicle

### ISSUE THREAD

**Issue by DavidCalles** [DavidCalles/Wi-Fi-Analizer-Robot#9]

**Comment by DavidCalles** [comment]
The robot was completely assembled. Just missing to incorporate the new Lidar sensor.

**Comment by peakymonk** [comment]
assembled the robot parts. motor, chassis, camera mount, driver board, all the sensor required and raspberry pie

**Comment by MReyes-1** [comment]
assembled the robot parts. motor, chassis, camera mount, driver board, all the sensor required and raspberry pie
